# Generated by Django 4.0.3 on 2022-04-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('birthday', models.DateTimeField()),
                ('gender', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
